### ISSUE TITLE
3.0.0 Tasks

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/FOSElasticaBundle#504]
- [x] Build a change log of any breaking or important changes since 2.x
- [x] Make sure any new documentation added since the documentation refactoring was started is migrated to the new documentation - #435
- [x] HTTP Headers for Elastica clients - #496 
- [x] KnpPaginator sorting functionality - #485
- [x] More code coverage! - #436
- [x] Hot swappable reindexing - #463 
- [x] Document hot swappable reindexing
- [x] Moving indexing to postFlush by default - #415
- [x] Disable logger in production by default (set logger to be enabled when kernel.debug is true)
- [x] General mapping options for a type - #343
- [x] Document best practices for large reindexing / memory usage and speed - #87
